[versions]
agp = "8.11.2"
kotlin = "2.2.20"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.13.0"
activity = "1.11.0"
constraintlayout = "2.2.1"
lottieV="6.6.10"
googleServiceV="4.4.4"
firebaseAuthV="24.0.1"
firebaseDataBaseV="22.0.1"
imagePickerV="2.1"
glideV="5.0.5"
lifecycleV = "2.9.4"
playServicesLocationV = "21.3.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
lottie = {group = "com.airbnb.android", name = "lottie", version.ref = "lottieV"}
firebase-auth = {group = "com.google.firebase", name = "firebase-auth", version.ref = "firebaseAuthV"}
firebaseDatabase = {group = "com.google.firebase", name = "firebase-database", version.ref = "firebaseDataBaseV"}
imagePicker={group = "com.github.dhaval2404", name = "imagepicker", version.ref = "imagePickerV"}
glide = {group = "com.github.bumptech.glide", name = "glide", version.ref = "glideV"}
lifecycle = {group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleV"}
playServicesLocation = {group = "com.google.android.gms", name = "play-services-location", version.ref = "playServicesLocationV"}

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
googleService = {id = "com.google.gms.google-services", version.ref = "googleServiceV"}
